---
title: "Er det høyde som bestemmer inntekt?"
author: "Ole Alexander Bakkevik & Sindre M. Espedal"
subtitle: Assignment 2 - MSB 105
output:
  html_document: default
  pdf_document: default
lang: no-NB
bibliography: OAB_SME_ASS_2.bib
csl: apa-no-ampersand.csl
---

```{r setup, message=FALSE, echo = FALSE}
library(dplyr)
library(tidyverse)
library(modelr)
library(ggplot2)
library(hrbrthemes)
library(huxtable)
library(knitr)
library(car)
library(bibtex)
options(scipen = 666)
knitr::opts_chunk$set(echo = TRUE)
```

# Introduksjon

I dette assignmentet skal vi besvare på problemstillingen "*er det høyde
som bestemmer inntekt?*". 
Vi benytter datasettet **heights** i pakken **modelr** for å svare på problemstillingen.

# Litteraturgjennomgang

Det argumenteres for at fysiske egenskaper spiller en sentral rolle i interaksjoner og resultater i arbeidslivet og det er aktiv litteratur som fokuserer på hvordan attraktivitet, vekt og kroppsbilde påvirker interaksjoner og resultater på arbeidsplassen [@judge2004]. For eksempel høyere individer vurderes som mer overbevisende [@young1996] og mer attraktive som kamerater [@freedman1980].

I studien "*The Effect of Physical Height on Workplace Success and Income: Preliminary Test of a Theoretical Model*" fokuserer de på hvilken rolle egenskapen høyde har på suksess i arbeidslivet, målt i inntekt. I studien kommer det frem at resultatene som er presentert i artikkelen tyder tydelig på at fysisk høyde
påvirker folk karrier og interaksjoner på arbeidsplassen og er derfor
verdig til fortsatt vitenskapelig undersøkelse [@judge2004].




# Litteraturliste


